version: '3.8'

services:
  web:
    build: ./inno_afisha
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./inno_afisha/:/usr/src/inno_afisha/
    ports:
      - 8000:8000
    env_file:
      - .env.dev

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=InnopolisUniversity
      - POSTGRES_DB=inno_afisha

volumes:
  postgres_data: