# Generated by Django 4.0 on 2022-10-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('picture', models.CharField(blank=True, default='', max_length=5000, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('rating', models.IntegerField()),
                ('location', models.CharField(max_length=500)),
                ('contacts', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'Events',
            },
        ),
    ]
